# Module manifest for module 'pOSINT'
# Generated by: ecstatic-nobel
# Generated on: 3/7/19


@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'pOSINT.psm1'
    
    # Version number of this module.
    ModuleVersion = '2.0.1'
    
    # Supported PSEditions
    # CompatiblePSEditions = @()
    
    # ID used to uniquely identify this module
    # GUID = ''
    
    # Author of this module
    Author = 'ecstatic-nobel'
    
    # Company or vendor of this module
    # CompanyName = ''
    
    # Copyright statement for this module
    Copyright = '(c) 2019 ecstatic-nobel. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'Gather Open-Source Intelligence using PowerShell.'
    
    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '3.0'
    
    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''
    
    # Minimum version of the PowerShell host required by this module
    PowerShellHostVersion = '3.0'
    
    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '4.5'
    
    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''
    
    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''
    
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()
    
    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @()
    
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess = @()
    
    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess = @()
    
    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @()
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'
    
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()
    
    # Variables to export from this module
    # VariablesToExport = '*'
    
    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()
    
    # DSC resources to export from this module
    DscResourcesToExport = @()
    
    # List of all modules packaged with this module
    ModuleList = @()
    
    # List of all files packaged with this module
    FileList = @('pOSINT.psd1','pOSINT.psm1','Search-AlienVault.ps1','Search-Crtsh.ps1','Search-EmailRep.ps1','Search-GreyNoise.ps1','Search-PhishingKitTracker.ps1','Search-PulseDive.ps1','Search-ThreatMiner.ps1','Search-Urlscan.ps1','Search-Censys.ps1','Search-Cymon.ps1','Search-HybridAnalysis.ps1','Search-ThreatCrowd.ps1','Search-Urlhaus.ps1','Search-VirusTotal.ps1')
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('pOSINT')
    
            # A URL to the license for this module.
            LicenseUri = 'https://github.com/ecstatic-nobel/pOSINT/blob/master/LICENSE'
    
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/ecstatic-nobel/pOSINT'
    
            # A URL to an icon representing this module.
            # IconUri = ''
    
            # ReleaseNotes of this module
            # ReleaseNotes = ''
    
        } # End of PSData hashtable
    
    } # End of PrivateData hashtable
    
    # HelpInfo URI of this module
    HelpInfoURI = 'https://github.com/ecstatic-nobel/pOSINT'
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}
    